### ISSUE TITLE
Suggestion: Rename `if-failed` to `when-failed`

### ISSUE THREAD

**Issue by samumbach** [adambard/failjure#1]
First of all, this is **awesome**! Thanks @adambard :sparkles: :+1:

As I read your [introductory blog post](https://adambard.com/blog/introducing-failjure/), I had an initial reaction when I saw `if-failed`:

``` clj
(f/attempt-all [,,,]
  ,,,
  (f/if-failed [e]
    (log-error (f/message e))
    (handle-error e)))
```

I saw two forms after `if` and my first intuition was that they would be "then" and "else" cases. This obviously doesn't make sense here, so this didn't hang me up for long.

...But, maybe we could avoid even the chance of momentary confusion by renaming to `when-failed`.

**Comment by adambard** [comment]
Good point! I'll leave if-failed in just in case someone's using it though.

**Comment by samumbach** [comment]
Awesome! Was going to suggest updating the README as well, but it looks like you already have (commit f7694ce) 👍
