### ISSUE TITLE
ok? for multiple results

### ISSUE THREAD

**Issue by lamuria** [adambard/failjure#11]
I was wondering if makes sense for change the `ok?` fn to also validate a list of results?

```clojure
(defn ok?
  [v]
  (if (coll? v)
    (every? ok? v)
    (not (failed? v))))
```

I think would be nice to add a feature like this or on the other hand if you want to have a different function with it's own semantic we can just add a different fn.

your thoughts on this one @adambard

**Comment by adambard** [comment]
I'm not a big fan of this sort of overloading -- it doesn't really add much value over the user just defining their own `(partial every? ok?)` if they need it for collections, and it's just not obvious that ok? would work this way on collections. I can imagine a situation where one might use failures at two levels, one per item of the collection that may return a failure, and one for the job that produces the collection which may itself fail. In this case the behavior you mentioned might be undesirable.
