### ISSUE TITLE
Monads dep was removed

### ISSUE THREAD

**Issue by ascho** [adambard/failjure#12]
Hello @adambard !
You removed monads dependency from failjure lib.
I am using previous failjure version in my project and i am using it as a monad in several places. 
For example, m-map over collection where projection function can return error.

Can you enlighten me why did you removed monad dependency?
Is it Occam Razor application?

Thanks!

**Comment by adambard** [comment]
Sorry for the breaking change, it escaped my notice that someone might be
using the monad directly! I hope it will not be too difficult to adapt;
this commit will probably be useful:
https://github.com/adambard/failjure/commit/d6d5b98fa8c9f307e2d2b31cf29bdb20b52d53b8

The notion that fewer deps are better is part of my reasoning, but also a
desire to open the way for the clojurescript port that I haven't yet gotten
around to doing.

**Comment by ascho** [comment]
@adambard thank you for explanation!
I will surround latest failjure version with monad support in my project
