### ISSUE TITLE
Destructuring inside attempt-all causes an exception/failjure that would normally be short-circuited not to be

### ISSUE THREAD

**Issue by chrismurrph** [adambard/failjure#15]
De-structuring inside `attempt-all` causes a returned java Exception or failjure Failure that would normally be short-circuited to not be short-circuited.

```clojure
(f/attempt-all [m (f :a)
                {:keys [a b c]} m]
          3)
```
The above code gets around the problem. The problem would be evident if you avoided having `m`, so directly de-structured. Obviously `f` is returning something that `f/attempt-all` ought to be catching (a  java Exception or failjure Failure).

**Comment by adambard** [comment]
Thanks to @ashwinbhaskar, this issue is resolved in 1.4.0
