### ISSUE TITLE
Proposal: failure handling without binding

### ISSUE THREAD

**Issue by ACiep** [adambard/failjure#21]
I don't see any way to handle failure without binding it to a symbol. `attempt-all` is great but if we have only one binding then there's a lot of boilerplate and nesting. My proposal is to add `attempt` macro which will let us handle failure without having to bind it manually.

Example with `attempt-all`:
```clojure
(f/attempt-all [result (f/fail "Failed")]
  result
  (f/when-failed [e] (handle-error e)))
```
Boilerplate. We don't do anything with the result if there's no error.
___
Example with `when-let-failed?`:
```clojure
(f/when-let-failed? [result (f/fail "Failed")]
  (handle-error result))
```
Less boilerplate, but we have to customize auto-indent and our code is less linear + we still have to name result
>"There are only two hard things in Computer Science: cache invalidation and naming things."
_Phil Karlton_
___
Example with `attempt`:
```clojure
(f/attempt (f/fail "Failed") handle-error)
```
0 boilerplate, elegant one-liner.
___
Example of real world use-case with `when-let-failed?`:
```clojure
(defn create-todo [input]
  (f/when-let-failed? [result (f/ok->input
                               (validate)
                               (prepare)
                               (insert-into-db!)
                               (result-json))]
    (create-todo-error result)))
```
___
Example of real world use-case with `attempt`:
```clojure
(defn create-todo [input]
  (f/attempt
    (f/ok-> input
            (validate)
            (prepare)
            (insert-into-db!)
            (result-json))
    create-todo-error)))
```

Ideal name imo would be `when-failed` but there's already macro with this name so `attempt` seams reasonable. It's almost like `attempt-all` but you attempt to get only one value and if there's only one value there's no point to bind it to anything

**Comment by adambard** [comment]
This is a good proposal! I may get to it over the holidays, but if you're reading this in the meantime, it looks like this:

```
(defn attempt [v handle-fn]
  (if (f/failed? v) (handle-fn v) v))
```

**Comment by adambard** [comment]
@ACiep `attempt` is now present in 2.1.1

**Comment by ACiep** [comment]
Nice. I was just about to sit down and do it but I see you was first :)
