### ISSUE TITLE
Allow arbitrary data to be associated with failure?

### ISSUE THREAD

**Issue by caleb** [adambard/failjure#3]
My code often fails in varying and spectacular ways :)

What would you think about allowing arbitrary maps to be associated with failures as well as strings?

My database might fail and my `Validateur` validations might fail, and I need to be able to render those in different ways.

If I could add a map to a failure then I could put the error map from `Validateur` into my failure and render that on my front end.

What do you think? Looking at your library and learning about monads has really changed the way I think about error handling, thanks!

**Comment by caleb** [comment]
I just realized that I can implement the HasFailed protocol with whatever I want. I'm guessing that would do the trick.

Again, thanks@

**Comment by adambard** [comment]
I think it's definitely worth documenting at least, so I've just gone and done that. Thanks!
