### ISSUE TITLE
Plans for clojurescript support?

### ISSUE THREAD

**Issue by twashing** [adambard/failjure#6]
@adambard Have you tried porting Failjure to clojurescript? Failjure uses algo.monads, which just seems to use one function `name-with-attributes`, from clojure.tools.macro. Ie, it doesn't support clojurescript. But [Cats](https://funcool.github.io/cats/latest) does.

Anyways, I thought it would be really nice to reuse tha same Either / Error monadic semantics, on both layers of our application. 

Thoughts?

**Comment by adambard** [comment]
I haven't tried and have no specific plans, but I'm definitely not opposed to the idea. Honestly the dependency on algo.monads could probably be eliminated without too much work.

**Comment by twashing** [comment]
@adambard Well I'm definitely interested in using failjure in both clj and cljs. Id otherwise have to figure out how to use Cats in cljs anyways. I think the [Either](https://funcool.github.io/cats/latest/#either) monad is what we'd want. But I don't see the`Either` type in [the code](https://github.com/funcool/cats/blob/master/src/cats/monad/either.cljc). Just `Left` and `Right` return types.

Anyways, if somehow you do get failjure on clj and cljs, I'm in. Maybe let me know if there's anything I can do to help.
